https://learn.365datascience.com/courses/linear-algebra-and-feature-selection/solving-quadratic-equations/

https://learn.365datascience.com/courses/linear-algebra-and-feature-selection/why-quadratic-equations-are-more-than-just-a-formula/

# __Linear Algebra__

Linear Independence of vectors, Linear Span and Basis vectors

Linear combination of vectors

A set of vectors is linearly independent if none of the vectors can be written as a linear combination of the others. If one vector can be written as a linear combination of the others, the set is linearly dependent.

Linear Independence of vectors - A set consists of linearly independent vectors when none of them are in the linear span of the rest of the vectors.

The Linear span of $e_2$ is the set of all vectors multiplied by $e_2$.

A set of vectors is linearly dependent if there is a linear combination of them with non-zero coefficients that equals zero.

https://learn.365datascience.com/courses/linear-algebra-and-feature-selection/smart-features-smarter-models-how-linear-independence-fuels-ai/



## __1. Introduction to Linear Algebra__
It is a branch of mathematics essential for understanding data science. Despite its vastness, the basic concepts of linear algebra are invaluable to data scientists and machine learning practitioners. Linear algebra is the study of vectors.
- An arrow with the same direction often represents it as the quantity and a length proportional to the magnitude of the quantity.
- Vectors are ordered lists of finite numbers.
- Vectors are the most fundamental mathematical objects in data science.

In linear algebra, data is often represented using linear equations. Matrices and vectors represent these. They simplify the process of representing large amounts of information.

- A matrix consists of rows and columns of numbers, variables, or expressions.
- Reducing data dimensions or choosing the right hyperparameters is crucial when building machine learning models.
- In cases where complex operations are involved in data science tasks, such as reducing data dimensions or selecting optimal hyperparameters for machine learning models, the use of mathematical notation and formalized concepts from linear algebra can be especially helpful.

## __2. Scalars and Vectors__

__Scalars:__ Measurable quantities, such as length, area, and volume, can be fully determined by specifying only their magnitude.(0-D)

__Vectors:__ A vector quantity is a physical quantity that has direction and magnitude. For example, velocity, force, and acceleration require a magnitude and a direction for their description. Geometrically, arrows or directed line segments typically represent vectors. There can be row vectors or column vectors. (1-D) (`m x 1` or `1 x m`)

__Matrix__: In linear algebra, a matrix is a collection of vectors, containing `m` rows and `n` columns. `(m x n)`.

## __3. Tensors__
- Scalar has lowest dimensionality which is (1 x 1).
- Vector has (m x 1) or (1 x m) dimensionality which each element is a scalar.
- Matrices has (m x n) dimensionality which are a collection of vectors.
- Scalars, Vectors and Matrices are all tensors of Rank 0, 1 and 2 respectively.
- Tensor of Rank 3 has dimensions (k x m x n) which can be seen as a collection of matrices.

__Vectors when transformed - do not change the direction but only gets scaled are called Eigen vectors and the factor by which they get scaled up are called Eigen values.__

## __3. Basis of a Vector Space__

Vector Space is a set of vectors than can be added and subtracted together, as well as multiplied by numbers called scalars. 

Basis of a Vector Space is a set of vectors whose number equals the dimension of that space. The notion of a spaces dimension is determined by its basis. So, basis of a Vector Space is a set of vectors that are linearly independent of each other. Their linear span is the entirety of the vector space. 
- A basis is a set of vectors that form the vector space.
- Any vector in the vector space is in the span of the basis.
- This means that in order to obtain any vector from a certain vector space, it is sufficient to know its basis vectors from which we can make a linear combination of them to achieve that. In short, the basis is the smallest set of vectors that generates the vector space.
-  For 2-D vectors, $e_1$ and $e_2$ form the basis of a vector space, i.e. they span the whole 2-dimensional space.

## __4. Vector Operations__
Vectors should have the same length to be added or subtracted. Multiplication of vectors is also called __Scaling__.

<span><img src=https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_3.png  width=400/>
<img src=https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_4.png  width=400/></span>
<img src=https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_5.png  width=800/>

- Dot product between 2 vectors always produces a scalar.

### __Example of the Dot and Cross Product of Two Vectors__

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_05_Data_Visualization/vectora.png)

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_6.png)

In [19]:
import numpy as np

### __Python Code Snippet for Dot and Cross Product__
- The dot product works in any number of dimensions, but the cross product only works in 3D.
- The dot product produces a scalar quantity, while the cross product produces a vector quantity.
- The dot product measures how much two vectors point in the same direction, while the cross product measures how much two vectors point in different directions.
- The cross product is also known as the vector product, and the dot product is also known as the scalar product.

Let's see the code for the dot product.

In [146]:
# Define a function to calculate dot product of two matrices

def dot_product(x,y):

    # Ensure that both the vectors have same length
    return sum(i*j for i,j in zip(x,y))

In [148]:
# Dot product of 1-D arrays

dot_product([3,2,6],[1,7,-2])

5

<b>Note: </b>In the above code, the zip function ensures both vectors have the same length.


When dot_product([3,2,6],[1,7,-2]) is called, the output will be 5.

#### __Using Numpy to find the Dot Product__

In [301]:
# Dot product of 1-D arrays

A = [3,2,6]
B = [1,7,-2]

In [303]:
dot_product = np.dot(A,B)
dot_product

5

In [170]:
# Dot product of 2-D arrays or matrices

A = np.array([[2,6,-1],[2,8,0],[9,8,7]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [289]:
A

array([[ 2,  6, -1],
       [ 2,  8,  0],
       [ 9,  8,  7]])

In [172]:
matrix_dot = np.dot(A,B)
matrix_dot

array([[ 19,  26,  33],
       [ 34,  44,  54],
       [ 90, 114, 138]])

In [120]:
# Define a function to calculate cross product of two vectors

def cross_product(u, v):
    q0 = u[1]*v[2] - u[2]*v[1]
    q1 = u[2]*v[0] - u[0]*v[2]
    q2 = u[0]*v[1] - u[1]*v[0]
    return [q0, q1, q2]

In [122]:
# Define vectors of same length

u = [1, 4, 5]
v = [2, -3, 6]

In [124]:
# Calculate the cross product
cross_product_result = cross_product(u, v)
cross_product_result

[39, 4, -11]

#### __Using Numpy to find the Cross Product__

In [159]:
# Cross product of 1-D arrays

cross_product = np.cross(u, v)
print(cross_product)
print(cross_product.shape)

[ 39   4 -11]
(3,)


In [184]:
A = [3,2,6]
B = [1,7,-2]

cross_product = np.cross(A, B)
cross_product

array([-46,  12,  19])

In [176]:
# Cross product of 2-D arrays or matrices

A = np.array([[2,6,-1],[2,8,0],[9,8,7]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [178]:
cross_product = np.cross(A, B)
cross_product

array([[ 20,  -7,  -2],
       [ 48, -12, -22],
       [ 16, -32,  16]])

## __4. Norm of a Vector__

The norm of a vector, often referred to as the vector's magnitude or length, is a measure of its length from the origin in Euclidean space.

The most commonly used norm is the Euclidean norm, which is defined as:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_7.png)


This is essentially the distance of the point defined by the vector from the origin (0, 0, ..., 0) in
n-dimensional space.

**Example:** <br>
A numerical example of the norm of a vector:


![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_8.png)

### __Python Code to Find the Norm of a Vector__

 The Python code for finding the norm of a vector is as follows:

In [31]:
# Define vector
v = [-1, -2, 3, 4, 5]

In [32]:
# Define function to calculate norm of a vector
import math
def norm_vector(v):
    dot_product = sum(i*i for i in v)
    return math.sqrt(dot_product)

In [33]:
# Call the function
norm_vector(v)

7.416198487095663

#### __Using Numpy to find Norm of a Vector__

In [35]:
np.linalg.norm(v)

7.416198487095663

In [36]:
v1 = np.array([ 8,1])
v

[-1, -2, 3, 4, 5]

In [37]:
np.linalg.norm(v1)

8.06225774829855

## __6. Matrix and Matrix Operations__


A matrix is a rectangular array of numbers or expressions, arranged in columns and rows. It is used to represent
a mathematical object or a property of the object.

![matrixex.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/matrixex.PNG)


If X[aij] and Y[bij] are $ m\times n $ matrices, their sum X+Y is an $ m\times n $ matrix obtained by adding the corresponding elements.

![additionordwr.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/additionordwr.PNG)


#### __Example: Matrix Addition of 3 x 3 Matrices__



![matrixexampleadd.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/matrixexampleadd.PNG)

### __Python Implementation for the Addition of Two Matrices with Same Order__

In [44]:
# Define a function to add matrices

def matrix_addition(x,y):
    xrows = len(x)
    xcols = len(x[0])
    yrows = len(y)
    ycols= len(y[0])
    if xrows!=yrows or xcols!=ycols:
        print("Sum is not defined as the matrices have different orders")
    else:
        result=[[0 for i in range(xcols)] for i in range(xrows)]
        for i in range(xrows):
            for j in range(xcols):
                result[i][j] = matrix_X[i][j]+matrix_Y[i][j]
        return result

In [63]:
# Take input from the user for first matrix

print("Enter the rows and columns of first matrix")
rows1 = int(input("Enter the number of rows : " ))
column1 = int(input("Enter the number of columns: "))

Enter the rows and columns of first matrix


Enter the number of rows :  2
Enter the number of columns:  2


In [67]:
print("Enter the elements of first Matrix:")
matrix_X= [[int(input()) for i in range(column1)] for i in range(rows1)]
print("First matrix is: ")
for n in matrix_X:
    print(n)


Enter the elements of first Matrix:


 1
 2
 3
 4


First matrix is: 
[1, 2]
[3, 4]
Enter the rows and columns of second matrix


Enter the number of rows :  2
Enter the number of columns:  2


In [ ]:
# Take input from the user for second matrix

print("Enter the rows and columns of second matrix")
rows2 = int(input("Enter the number of rows : " ))
column2 = int(input("Enter the number of columns: "))

In [69]:
print("Enter the elements of second matrix:")
matrix_Y= [[int(input()) for i in range(column2)] for i in range(rows2)]
for n in matrix_Y:
    print(n)

Enter the elements of second matrix:


 5
 6
 7
 8


[5, 6]
[7, 8]


In [71]:
# Return the value of function
matrix_addition(matrix_X,matrix_Y)

[[6, 8], [10, 12]]

The code takes two matrices of the same order and adds them. If the matrices are of a different order, it prints an error code, indicating the same.

## __7. Scalar Multiplication__

Scalar multiplication of a matrix refers to each element of the matrix being multiplied by the given scalar.

If X is an $ m\times n $ matrix and C is a scalar, then CX is the $ m\times n $ matrix obtained by multiplying every element of X with C.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_9.png)


![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_10.png)

### __Python Code Snippet for Scalar Multiplication__

This snippet takes a scalar value and a matrix as input and gives a resultant matrix, the elements of which are the products of the original matrix and the scalar value.


In [11]:
# Define function for scalar multiplication
def scalar_multiplication(c,X):
    cX = X
    for i in range(len(X)):
        for j in range(len(X[0])):
            cX[i][j] = c*cX[i][j]
    return cX

In [12]:
scalar_multiplication(-3,[[2,6,-1],[2,8,0],[9,8,7]])

[[-6, -18, 3], [-6, -24, 0], [-27, -24, -21]]

#### __Using Numpy to perform scalar multiplication__

In [10]:
A = np.array([[2,6,-1],[2,8,0],[9,8,7]])

In [11]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
Matrix_add = A + B

Matrix_add

array([[ 3,  8,  2],
       [ 6, 13,  6],
       [16, 16, 16]])

In [20]:
C = np.array([[1,2],[3,4]])

In [21]:
D = np.array([[5,6],[7,8]])

In [22]:
matrix_dot = np.dot(C,D)
matrix_dot

array([[19, 22],
       [43, 50]])

In [23]:
Element_multi = A * B
Element_multi

array([[ 2, 12, -3],
       [ 8, 40,  0],
       [63, 64, 63]])

In [24]:
C = np.array([1,2,3,4])

In [26]:
C

array([1, 2, 3, 4])

In [27]:
transpose_C = C.T

In [28]:
transpose_C

array([1, 2, 3, 4])

In [29]:
transpose_A = A.T

In [30]:
transpose_A

array([[ 2,  2,  9],
       [ 6,  8,  8],
       [-1,  0,  7]])

In [31]:
A

array([[ 2,  6, -1],
       [ 2,  8,  0],
       [ 9,  8,  7]])

## __8. Matrix Operations__


### __8.1 Matrix Subtraction__
The subtraction of matrices involves element-wise subtraction. If X[$a_{ij} $ ]and Y[$b_{ij} $ ]are $ m\times n $ matrices, their difference X-Y is the  $ m\times n $  matrix obtained by subtracting the corresponding elements of Y from those of X.

So, X-Y = [$a_{ij} $ - $b_{ij} $]



![suboperation.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/suboperation.PNG)


If X and Y are of different orders, then subtraction is not possible.

#### __Example__





![examsub.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/examsub.PNG)

#### __Python Code Snippet to Perform Matrix Subtraction__

In the code, matrix_subtraction will take two matrices, and it will first check the order of the matrices. If it is the same, then perform a subtraction operation; otherwise, it prints an error message.


In [188]:
# Define function for subtraction of matrices

def matrix_subtraction(x,y):
    xrows = len(x)
    xcols = len(x[0])
    yrows = len(y)
    ycols= len(y[0])
    if xrows!=yrows or xcols!=ycols:
        print("Subtraction is not defined as the matrices have different orders")
    else:
        result=[[0 for i in range(xcols)] for i in range(xrows)]
        for i in range(xrows):
            for j in range(xcols):
                result[i][j] = matrix_X[i][j]-matrix_Y[i][j]
        return result

In [190]:
# Take input from the user for the first matrix

print("Enter the rows and columns of first matrix")
rows1 = int(input("Enter the number of rows : " ))
column1 = int(input("Enter the number of columns: "))

Enter the rows and columns of first matrix


Enter the number of rows :  2
Enter the number of columns:  2


In [192]:
print("Enter the elements of first matrix:")
matrix_X= [[int(input()) for i in range(column1)] for i in range(rows1)]
print("First matrix is: ")
for n in matrix_X:
    print(n)

Enter the elements of first matrix:


 1
 2
 3
 4


First matrix is: 
[1, 2]
[3, 4]


In [194]:
# Take input from the user for the second matrix

print("Enter the rows and columns of second matrix")
rows2 = int(input("Enter the number of rows : " ))
column2 = int(input("Enter the number of columns: "))

Enter the rows and columns of second matrix


Enter the number of rows :  2
Enter the number of columns:  2


In [196]:
print("Enter the elements of second matrix:")
matrix_Y= [[int(input()) for i in range(column2)] for i in range(rows2)]
for n in matrix_Y:
    print(n)

Enter the elements of second matrix:


 5
 6
 7
 8


[5, 6]
[7, 8]


In [200]:
matrix_subtraction(matrix_X, matrix_Y)

[[-4, -4], [-4, -4]]

#### __Using Numpy for matrix subtraction__ ####

In [205]:
A = np.array([[2,6,-1],[2,8,0],[9,8,7]])

In [207]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [209]:
Matrix_sub = A - B
Matrix_sub

array([[ 1,  4, -4],
       [-2,  3, -6],
       [ 2,  0, -2]])

### __8.2 Matrix Multiplication__
The product of two matrices is obtained by multiplying the elements of the rows of the first matrix with the corresponding elements of the columns of the second matrix.

![matrizmulti1.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/matrizmulti1.PNG)




![multi2.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/multi2.PNG)

If X is an $ m\times n $ matrix and Y is an $ n\times r $, then their product Z =
$ X\times Y $ is an $ m\times r $ matrix, whose elements are given by the following expression:


$Z_{ij} $ = X $_{i1} $Y $_{1j} $ + X $_{i2} $Y $_{2j} $ +.... X $_{in} $ Y $_{nj} $

![multi3.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/multi3.PNG)

#### __Example__



Consider two matrices X and Y, where the order of X is 2X3 and the order of Y is 3X2.

![multi4.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/multi4.PNG)


### __Python Code Snippet for the Matrix Multiplication__

In [ ]:
# Define function to perform matrix multiplication
def matrix_multiplication(x,y):
    xrows = len(x)
    xcols = len(x[0])
    yrows = len(y)
    ycols= len(y[0])
    if xcols!=yrows:
        print ("Product is not defined as the no. of rows in the first matrix is not equal to the number of columns in the second matrix")
    else:
        z = [ [ 0 for i in range(ycols) ] for j in range(xrows) ]
        for i in range(xrows):
            for j in range(ycols):
                total = 0
                for ii in range(xcols):
                    total += x[i][ii] * y[ii][j]
                    z[i][j] = total
        return z


In [ ]:
# Take input from user
print("Enter the rows and columns of first matrix")
rows1 = int(input("Enter the number of rows : " ))
column1 = int(input("Enter the number of columns: "))

print("Enter the elements of first matrix:")
matrix_X= [[int(input()) for i in range(column1)] for i in range(rows1)]
print("First matrix is: ")
for n in matrix_X:
    print(n)
print("Enter the rows and columns of second matrix")
rows2 = int(input("Enter the number of rows : " ))
column2 = int(input("Enter the number of columns: "))

print("Enter the elements of second matrix:")
matrix_Y= [[int(input()) for i in range(column2)] for i in range(rows2)]
for n in matrix_Y:
    print(n)

Enter the rows and columns of first matrix


Enter the number of rows :  2
Enter the number of columns:  2


Enter the elements of first matrix:


 3
 4
 5
 6


First matrix is: 
[3, 4]
[5, 6]
Enter the rows and columns of second matrix


Enter the number of rows :  2
Enter the number of columns:  2


Enter the elements of second matrix:


 5
 6
 7
 8


[5, 6]
[7, 8]


In [ ]:
matrix_multiplication(matrix_X,matrix_Y)

[[43, 50], [67, 78]]

When two matrices of order 2X3 and 3X2 are multiplied, the output will be in 2X2 matrix.

### __8.3 Transpose of a Matrix__
The transpose of a matrix is obtained by swapping its rows and columns. It is basically the same matrix with flipped axes.
- The transpose of matrix X of size $ m\times n $ results in an $ n\times m $ matrix, denoted as $ X^T $.
- This is achieved by interchanging the rows and columns of X.

![trans1.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/trans1.PNG)


#### __Example__

X is a 2X3 matrix. The transpose $ X^T $  of X will be 3X2 matrix.

![transnew.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/transnew.PNG)

#### __Python Implementation for Finding the Transpose of a Matrix__

In [234]:
# Define function to perform transpose of matrix

def matrix_transpose(x):
    xrows = len(x)
    xcols = len(x[0])
    z = [ [ 0 for i in range(xrows) ] for j in range(xcols) ]
    for i in range(xcols):
        for j in range(xrows):
            z[i][j] = x[j][i]
    return z

In [217]:
matrix = [[1,9,-6],[5,3,-7]]
matrix

[[1, 9, -6], [5, 3, -7]]

In [219]:
matrix_transpose(matrix)

[[1, 5], [9, 3], [-6, -7]]

#### __Using Numpy to find the transpose of a matrix__ ####

In [222]:
C = np.array([1,2,3,4])
C

array([1, 2, 3, 4])

In [224]:
transpose_C = C.T
transpose_C

array([1, 2, 3, 4])

In [226]:
A

array([[ 2,  6, -1],
       [ 2,  8,  0],
       [ 9,  8,  7]])

In [228]:
transpose_A = A.T
transpose_A

array([[ 2,  2,  9],
       [ 6,  8,  8],
       [-1,  0,  7]])

In [238]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [240]:
transpose_B = B.T
transpose_B

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## __9. Rank of a Matrix__

The rank of a matrix is defined as the maximum number of linearly independent columns or rows in the matrix.
![trans3.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/trans3.PNG)             

**Note:** To find the rank of a matrix, first convert it into the row echelon form.

For a matrix to be in its echelon form, it must follow these three rules:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_11.png)

#### __Example__

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_12.png)

The output, after using elementary transformations, is shown below:

**R2 → R2 – 2R1**

**R3 → R3 – 3R1**

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_13.png)

**R3 → R3 – 2R2**

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_14.png)

The above matrix is in row-echelon form.

Since the number of non-zero rows is 2, **the rank of the matrix is 2.**

In [32]:
A

array([[ 2,  6, -1],
       [ 2,  8,  0],
       [ 9,  8,  7]])

In [33]:
np.linalg.det(A)

84.00000000000006

## __9. Determinant of a Matrix and Identity Matrix__

The determinant of a matrix is a scalar quantity that is a function of the elements of the matrix.

- It is a number obtained from any square matrix.
- Determinants are defined only for square matrices.
- It identifies whether the matrix is invertible or not.
- A matrix is __Invertible__ if it is classified as a square matrix and its determinant $\neq$ 0.
- On the other hand, a matrix is __Non-Invertible__ if it is classified as a non-square matrix and its determinant = 0.
- These are useful in determining the solution of a system of linear equations.

                               Let X = [aij] be an nxn matrix, where n ≥2

<img src="https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_15.png" width=500 height=500 />


**Note:** The determinant of a non-square matrix is not defined. The determinant of a matrix X is denoted by det X or |X|.

https://learn.365datascience.com/courses/linear-algebra-and-feature-selection/basis-determinant-and-inverse-the-backbone-of-machine-learning-math/

**Consider the matrices 2X2 and 3X3:**

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_16.png)

   
Substitute the expressions for the determinant of a $ 2\times 2 $ matrix in the above equation. So, the output will be shown as below:

![det2.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/det2.PNG)

#### __Python Implementation for Finding the Determinant of a Matrix__

In [16]:
def determinant_3x3(matrix):
    if len(matrix) == 3 and all(len(row) == 3 for row in matrix):
        a, b, c = matrix[0]
        d, e, f = matrix[1]
        g, h, i = matrix[2]
        return a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    else:
        return "Matrix must be 3x3"

# Insert values in the matrix
matrix = [[5, 5, 3],
          [4, 5, 6],
          [7, 8, 9]]

det = determinant_3x3(matrix)
print("Determinant:", det)

Determinant: 6


## __10. Identity Matrix or Operator__
An identity matrix (I) is a square matrix that, when multiplied with a matrix X, gives the same result as X.

![det3.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/det3.PNG)

**Hint**: This is equivalent to the number 1 in the number system.






## __11. Inverse of a Matrix__

The inverse of a matrix (often denoted as X−1 for a matrix X) is a matrix that yields the identity matrix when multiplied with the original matrix.
- If X is a square matrix, then its inverse $ X^{-1} $ satisfies the following condition:


![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_17.png)


I is the $ n\times n $ identity matrix. If an $ X^{-1} $ exists for X, then X is described as invertible.

#### __Example__

X is a 2x2 matrix.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_18.png)

The diagonal elements of I are all 1, and all its non-diagonal elements are 0.

#### Example:
![det4.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/det4.PNG)

## __11. Inverse of a Matrix, Eigenvalues, and Eigenvectors__

### __11.1 Inverse of a matrix__



### __11.2 Minor__

The minor of an element in a matrix is the determinant of the square matrix formed by deleting the row and column containing that element.

For example,
consider the matrix D:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_05_Data_Visualization/cofactor_p1.png)


Then, the minor of a12 would be:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_05_Data_Visualization/stasminor_picture1.png)

### __11.3 Cofactor__

The cofactor of an element of a matrix is the determinant of the matrix obtained by eliminating the row and column in the matrix that contains the element and then multiplying by +1 or -1 according to the position of the element.

For example,
consider the matrix:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_05_Data_Visualization/cofactor_p1.png)

The cofactor of 2 would be:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_05_Data_Visualization/cofactor_p2.png)

To find the determinant:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_05_Data_Visualization/cofactor_p3.png)

By subtracting them, you get:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_05_Data_Visualization/cofactor_p4.png)

### __11.4 Adjoint Matrix__

The transpose of a cofactor matrix is an adjoint matrix.

### __Python Code for Finding the Inverse of a 2X2 Matrix__

In [17]:
def inverse_matrix_2x2(matrix):
    a, b, c, d = matrix[0][0], matrix[0][1], matrix[1][0], matrix[1][1]

    # Calculate the determinant
    determinant = a * d - b * c

    # Check if the matrix has an inverse
    if determinant == 0:
        return "This matrix does not have an inverse."

    # Calculate the inverse
    inverse = [[d / determinant, -b / determinant],
               [-c / determinant, a / determinant]]

    return inverse

# Example matrix
matrix = [[4, 7], [2, 6]]

# Calculate its inverse
inverse = inverse_matrix_2x2(matrix)
print("Inverse of the matrix:", inverse)

Inverse of the matrix: [[0.6, -0.7], [-0.2, 0.4]]


## __12. Eigenvalues and Eigenvectors__

__Eigenvalues__ are a special set of scalar values associated with the linear equations in matrix operations. Imagine you have a big box. You're asked to stretch or shrink everything inside the box, but only in certain directions. Eigenvalues tell you how much everything stretches or shrinks along those special directions.

__Eigenvectors__ represent directions in which the linear transformation has a stretching or compressing effect. Imagine you have arrows inside the box. These arrows represent different directions. Eigenvectors are the special arrows that don't change their direction when you apply force. They might get longer or shorter, but they still point in the same direction.

- A single eigenvalue can have many eigenvectors, but not the other way around.
- Eigenvalues and Eigenvectors are the scalar and vector quantities associated with matrices used for linear transformations.
- Eigenvectors are the directions that remain unchanged during a transformation, even if they get longer or shorter.
- Eigenvalues are the numbers that indicate how much something stretches or shrinks during that transformation.
- The vector that only changes by a scalar factor after applying a transformation is called an eigenvector, and the scalar value attached to the eigenvector is called the eigenvalue.
- The eigenvector v is a vector that, when transformed by the matrix A, remains in the same direction (or, in the case of a negative eigenvalue, in the opposite direction).
- The eigenvalue λ represents the scaling factor applied to the eigenvector during the transformation. 


An eigenvector v of a matrix A is a non-zero vector such that 

$$ \text{Av = λv} $$

where λ is a scalar called the eigenvalue. 


Suppose X is an $ n\times n $ matrix. When you multiply X with a new vector v, it does two things to the vector v:

1.	It scales the vector.
2.	It rotates the vector.


When X acts on a certain set of vectors, it results in scaling the vector and not changing the direction of the vector.
   *  These specific vectors, which you do not rotate but may stretch or compress, are called eigenvectors.
   * The amount by which these vectors stretch or compress is called the corresponding eigenvalue.

### __Finding Eigenvalues and Eigenvectors:__

__Eigenvalues__ are found by solving the characteristic equation:

   $$ \text{det(A - λI)} = 0 $$

where 
* A is the matrix,
* λ is the eigenvalue, and
* I is the identity matrix.
* det is the determinant of the expression


__Eigenvectors:__ Once the eigenvalues are found, the corresponding eigenvectors are determined by solving the equation
  
  $$ \text{(A - λI) v} = 0 $$

where 
- λ is the eigenvalue and
- v is the eigenvector. 

### __Applications:__

Eigenvalues and eigenvectors are used in the following areas:

- __Linear transformations:__ Eigenvalues and eigenvectors understand and analyze the behavior of linear transformations. They provide insights into how the transformation affects different directions in the vector space.
- __Differential equations:__ Eigenvalues and eigenvectors solve systems of ordinary and partial differential equations. They help find solutions that have exponential growth or decay behavior.
- __Structural analysis:__ In structural engineering, eigenvalues and eigenvectors analyze the stability and modes of vibration of structures.

### __Python Code for Finding the Eigenvalues and Eigenvectors of a 2X2 Matrix__

In [18]:
def find_eigenvalues(matrix):
    # Extract matrix elements
    a, b, c, d = matrix[0][0], matrix[0][1], matrix[1][0], matrix[1][1]

    # Calculate the trace and determinant of the matrix
    trace = a + d
    determinant = a * d - b * c

    # Use the quadratic formula to find eigenvalues
    eigenvalue1 = (trace + (trace**2 - 4 * determinant)**0.5) / 2
    eigenvalue2 = (trace - (trace**2 - 4 * determinant)**0.5) / 2

    return eigenvalue1, eigenvalue2

def find_eigenvectors(matrix, eigenvalues):
    eigenvectors = []
    for lambd in eigenvalues:
        # Solve for the eigenvector corresponding to each eigenvalue
        a, b, c, d = matrix[0][0], matrix[0][1], matrix[1][0], matrix[1][1]
        # Form the system (A -  lambda*I)*v = 0
        # where A is the matrix, lambda is the eigenvalue, and v is the eigenvector
        vec_matrix = [[a - lambd, b], [c, d - lambd]]
        # Assume the second component of the eigenvector is 1 (for simplicity)
        # The solution for the first component of the eigenvector
        if vec_matrix[0][0] != 0:  # Avoid division by zero
            eigenvector_first_component = -vec_matrix[0][1] / vec_matrix[0][0]
        else:
            eigenvector_first_component = 1
        eigenvectors.append([eigenvector_first_component, 1])
    return eigenvectors

# Define a 2x2 matrix
matrix = [[4, 2], [1, 3]]

# Find eigenvalues
eigenvalues = find_eigenvalues(matrix)
print("Eigenvalues:", eigenvalues)

# Find eigenvectors
eigenvectors = find_eigenvectors(matrix, eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: (5.0, 2.0)
Eigenvectors: [[2.0, 1], [-1.0, 1]]


## __13. Calculus in Linear Algebra__

Calculus is the branch of mathematics that studies continuous changes in quantities. It commonly measures quantities such as the slopes of curves or objects.

Calculus can be broadly divided into two types:

![differeninte.PNG](https://s3.us-east-1.amazonaws.com/static2.simplilearn.com/lms/testpaper_images/ADSP/Advanced_Statistics/LinearRegression/differeninte.PNG)

While the former concerns instantaneous rates of change and the slopes of curves, the latter explores the accumulation of quantities and areas under or between curves.

It is necessary for developing an intuition for machine learning algorithms.


### __13.1 Differential Calculus__

Differential calculus is applied in important machine learning algorithms like Gradient Descent. Gradient Descent is vital in the backpropagation of Neural Networks. It measures how the output of a function changes when the input changes in small amounts.







#### __Applications of Differential Calculus in Machine Learning Algorithms__



![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_06_Maths_and_Stats/Linear_Algebra/Image_20.png)



### __13.2 Integral Calculus__

Integral calculus is commonly used to determine the probability of events. For example, it helps you find the posterior in a Bayesian model or bound the error in a sequential decision per the Neyman-Pearson Lemma.

## **Important**

You have been performing matrix operations by defining individual functions for each one. Now, it's time to streamline your approach using the powerful NumPy library, which includes the `numpy.linalg` module. This change simplifies your code and enhances computational efficiency. NumPy allows you to perform complex matrix operations with concise and optimized functions. This eliminates the need for manually written, function-specific code. Embrace this shift to fully utilize Python's capabilities for handling linear algebra operations.

Below are the NumPy functions that you can explore:
    
- numpy.add(matrix1, matrix2)

- numpy.subtract(matrix1, matrix2)

- numpy.multiply(matrix1, matrix2)

- numpy.divide(matrix1, matrix2)

- numpy.dot(matrix1, matrix2)

- numpy.transpose(matrix)

- numpy.linalg.inv(matrix)

- numpy.linalg.det(matrix)

- numpy.linalg.eig(matrix)

- numpy.linalg.matrix_rank(matrix)

## __Assisted Practice__

### **Problem Statement:**

You are given two matrices, A and B. Use the NumPy library to perform various matrix operations. This exercise will help you grasp the fundamental concepts of linear algebra and their application in Python. Here are the two matrices:

Matrix A:

\begin{equation}
  \begin{bmatrix}
    4 & 7 \\
    2 & 6
  \end{bmatrix}
  \label{eq:aeqn}
\end{equation}

Matrix B:

\begin{equation}
  \begin{bmatrix}
    5 & 8 \\
    3 & 4
  \end{bmatrix}
  \label{eq:aeqn}
\end{equation}

**Steps to perform:**
- Add Matrix A and Matrix B
- Multiply Matrix A and Matrix B
- Transpose Matrix A
- Find the determinant of Matrix B
- Find the inverse of Matrix A (if it exists)

**Note:** Compute the above operation using the NumPy library